spring:
  mail:
    host: ${spring.mail.host}
    port: ${spring.mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls: true
  data:
    elasticsearch:
      cluster-nodes: localhost:9200