name: github-action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    env:
      JASYPT_PASSWORD: ${{ secrets.JASYPT_PASSWORD }}

    steps:
      - name: Github Repository Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: make application-prod.yml
        run: |
          ./gradlew bootJar

      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Image Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_REPOSITORY_TAG_NAME }}

      - name: Copy Deployment Files to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          username: ${{ secrets.EC2_INSTANCE_USERNAME }}
          key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
          script: |
            whoami

      - name: Docker Container Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_INSTANCE_HOST }}
          username: ${{ secrets.EC2_INSTANCE_USERNAME }}
          key: ${{ secrets.EC2_INSTANCE_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_REPOSITORY_TAG_NAME }}
            docker stop $(docker ps -a -q)
            docker run -p 8080:8080 ${{ secrets.DOCKER_HUB_REPOSITORY_TAG_NAME }}
            docker rm $(docker ps --filter 'status=exited' -a -q)
            docker image prune -a -f